package yyz.njupt.view.netService.POJO;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegReq.proto

public final class RegReqProto {
  private RegReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 recCode = 1;
    /**
     * <code>required int32 recCode = 1;</code>
     */
    boolean hasRecCode();
    /**
     * <code>required int32 recCode = 1;</code>
     */
    int getRecCode();

    // required string recContend = 2;
    /**
     * <code>required string recContend = 2;</code>
     */
    boolean hasRecContend();
    /**
     * <code>required string recContend = 2;</code>
     */
    java.lang.String getRecContend();
    /**
     * <code>required string recContend = 2;</code>
     */
    com.google.protobuf.ByteString
        getRecContendBytes();

    // required string email = 3;
    /**
     * <code>required string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional string passwd = 4;
    /**
     * <code>optional string passwd = 4;</code>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 4;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    // optional string verification = 5;
    /**
     * <code>optional string verification = 5;</code>
     */
    boolean hasVerification();
    /**
     * <code>optional string verification = 5;</code>
     */
    java.lang.String getVerification();
    /**
     * <code>optional string verification = 5;</code>
     */
    com.google.protobuf.ByteString
        getVerificationBytes();
  }
  /**
   * Protobuf type {@code ReqReq}
   */
  public static final class ReqReq extends
      com.google.protobuf.GeneratedMessage
      implements ReqReqOrBuilder {
    // Use ReqReq.newBuilder() to construct.
    private ReqReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqReq defaultInstance;
    public static ReqReq getDefaultInstance() {
      return defaultInstance;
    }

    public ReqReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              recCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              recContend_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              passwd_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              verification_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RegReqProto.internal_static_ReqReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RegReqProto.internal_static_ReqReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RegReqProto.ReqReq.class, RegReqProto.ReqReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqReq> PARSER =
        new com.google.protobuf.AbstractParser<ReqReq>() {
      public ReqReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 recCode = 1;
    public static final int RECCODE_FIELD_NUMBER = 1;
    private int recCode_;
    /**
     * <code>required int32 recCode = 1;</code>
     */
    public boolean hasRecCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 recCode = 1;</code>
     */
    public int getRecCode() {
      return recCode_;
    }

    // required string recContend = 2;
    public static final int RECCONTEND_FIELD_NUMBER = 2;
    private java.lang.Object recContend_;
    /**
     * <code>required string recContend = 2;</code>
     */
    public boolean hasRecContend() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string recContend = 2;</code>
     */
    public java.lang.String getRecContend() {
      java.lang.Object ref = recContend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          recContend_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string recContend = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRecContendBytes() {
      java.lang.Object ref = recContend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recContend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>required string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string passwd = 4;
    public static final int PASSWD_FIELD_NUMBER = 4;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 4;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string passwd = 4;</code>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string verification = 5;
    public static final int VERIFICATION_FIELD_NUMBER = 5;
    private java.lang.Object verification_;
    /**
     * <code>optional string verification = 5;</code>
     */
    public boolean hasVerification() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string verification = 5;</code>
     */
    public java.lang.String getVerification() {
      java.lang.Object ref = verification_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          verification_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string verification = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVerificationBytes() {
      java.lang.Object ref = verification_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      recCode_ = 0;
      recContend_ = "";
      email_ = "";
      passwd_ = "";
      verification_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRecCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecContend()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, recCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRecContendBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getVerificationBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, recCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRecContendBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPasswdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getVerificationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RegReqProto.ReqReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegReqProto.ReqReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegReqProto.ReqReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegReqProto.ReqReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegReqProto.ReqReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RegReqProto.ReqReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RegReqProto.ReqReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RegReqProto.ReqReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RegReqProto.ReqReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RegReqProto.ReqReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RegReqProto.ReqReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RegReqProto.ReqReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RegReqProto.internal_static_ReqReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RegReqProto.internal_static_ReqReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RegReqProto.ReqReq.class, RegReqProto.ReqReq.Builder.class);
      }

      // Construct using RegReqProto.ReqReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        recCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        recContend_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        verification_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RegReqProto.internal_static_ReqReq_descriptor;
      }

      public RegReqProto.ReqReq getDefaultInstanceForType() {
        return RegReqProto.ReqReq.getDefaultInstance();
      }

      public RegReqProto.ReqReq build() {
        RegReqProto.ReqReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RegReqProto.ReqReq buildPartial() {
        RegReqProto.ReqReq result = new RegReqProto.ReqReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.recCode_ = recCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recContend_ = recContend_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.passwd_ = passwd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.verification_ = verification_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RegReqProto.ReqReq) {
          return mergeFrom((RegReqProto.ReqReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RegReqProto.ReqReq other) {
        if (other == RegReqProto.ReqReq.getDefaultInstance()) return this;
        if (other.hasRecCode()) {
          setRecCode(other.getRecCode());
        }
        if (other.hasRecContend()) {
          bitField0_ |= 0x00000002;
          recContend_ = other.recContend_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000008;
          passwd_ = other.passwd_;
          onChanged();
        }
        if (other.hasVerification()) {
          bitField0_ |= 0x00000010;
          verification_ = other.verification_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRecCode()) {
          
          return false;
        }
        if (!hasRecContend()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RegReqProto.ReqReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RegReqProto.ReqReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 recCode = 1;
      private int recCode_ ;
      /**
       * <code>required int32 recCode = 1;</code>
       */
      public boolean hasRecCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 recCode = 1;</code>
       */
      public int getRecCode() {
        return recCode_;
      }
      /**
       * <code>required int32 recCode = 1;</code>
       */
      public Builder setRecCode(int value) {
        bitField0_ |= 0x00000001;
        recCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 recCode = 1;</code>
       */
      public Builder clearRecCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        recCode_ = 0;
        onChanged();
        return this;
      }

      // required string recContend = 2;
      private java.lang.Object recContend_ = "";
      /**
       * <code>required string recContend = 2;</code>
       */
      public boolean hasRecContend() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string recContend = 2;</code>
       */
      public java.lang.String getRecContend() {
        java.lang.Object ref = recContend_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          recContend_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string recContend = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRecContendBytes() {
        java.lang.Object ref = recContend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recContend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string recContend = 2;</code>
       */
      public Builder setRecContend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        recContend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string recContend = 2;</code>
       */
      public Builder clearRecContend() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recContend_ = getDefaultInstance().getRecContend();
        onChanged();
        return this;
      }
      /**
       * <code>required string recContend = 2;</code>
       */
      public Builder setRecContendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        recContend_ = value;
        onChanged();
        return this;
      }

      // required string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // optional string passwd = 4;
      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 4;</code>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string passwd = 4;</code>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 4;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 4;</code>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 4;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        passwd_ = value;
        onChanged();
        return this;
      }

      // optional string verification = 5;
      private java.lang.Object verification_ = "";
      /**
       * <code>optional string verification = 5;</code>
       */
      public boolean hasVerification() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string verification = 5;</code>
       */
      public java.lang.String getVerification() {
        java.lang.Object ref = verification_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          verification_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string verification = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVerificationBytes() {
        java.lang.Object ref = verification_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          verification_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string verification = 5;</code>
       */
      public Builder setVerification(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        verification_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string verification = 5;</code>
       */
      public Builder clearVerification() {
        bitField0_ = (bitField0_ & ~0x00000010);
        verification_ = getDefaultInstance().getVerification();
        onChanged();
        return this;
      }
      /**
       * <code>optional string verification = 5;</code>
       */
      public Builder setVerificationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        verification_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqReq)
    }

    static {
      defaultInstance = new ReqReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014RegReq.proto\"b\n\006ReqReq\022\017\n\007recCode\030\001 \002(" +
      "\005\022\022\n\nrecContend\030\002 \002(\t\022\r\n\005email\030\003 \002(\t\022\016\n\006" +
      "passwd\030\004 \001(\t\022\024\n\014verification\030\005 \001(\tB\rB\013Re" +
      "gReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ReqReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ReqReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqReq_descriptor,
              new java.lang.String[] { "RecCode", "RecContend", "Email", "Passwd", "Verification", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
