package yyz.njupt.view.netService.POJO;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegResp.proto

public final class RegRespProto {
  private RegRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 respCode = 1;
    /**
     * <code>required int32 respCode = 1;</code>
     */
    boolean hasRespCode();
    /**
     * <code>required int32 respCode = 1;</code>
     */
    int getRespCode();

    // required string respContend = 2;
    /**
     * <code>required string respContend = 2;</code>
     */
    boolean hasRespContend();
    /**
     * <code>required string respContend = 2;</code>
     */
    java.lang.String getRespContend();
    /**
     * <code>required string respContend = 2;</code>
     */
    com.google.protobuf.ByteString
        getRespContendBytes();
  }
  /**
   * Protobuf type {@code RegResp}
   */
  public static final class RegResp extends
      com.google.protobuf.GeneratedMessage
      implements RegRespOrBuilder {
    // Use RegResp.newBuilder() to construct.
    private RegResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegResp defaultInstance;
    public static RegResp getDefaultInstance() {
      return defaultInstance;
    }

    public RegResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              respCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              respContend_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RegRespProto.internal_static_RegResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RegRespProto.internal_static_RegResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RegRespProto.RegResp.class, RegRespProto.RegResp.Builder.class);
    }

    public static com.google.protobuf.Parser<RegResp> PARSER =
        new com.google.protobuf.AbstractParser<RegResp>() {
      public RegResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 respCode = 1;
    public static final int RESPCODE_FIELD_NUMBER = 1;
    private int respCode_;
    /**
     * <code>required int32 respCode = 1;</code>
     */
    public boolean hasRespCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 respCode = 1;</code>
     */
    public int getRespCode() {
      return respCode_;
    }

    // required string respContend = 2;
    public static final int RESPCONTEND_FIELD_NUMBER = 2;
    private java.lang.Object respContend_;
    /**
     * <code>required string respContend = 2;</code>
     */
    public boolean hasRespContend() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string respContend = 2;</code>
     */
    public java.lang.String getRespContend() {
      java.lang.Object ref = respContend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          respContend_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string respContend = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRespContendBytes() {
      java.lang.Object ref = respContend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respContend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      respCode_ = 0;
      respContend_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRespCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRespContend()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, respCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRespContendBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, respCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRespContendBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RegRespProto.RegResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegRespProto.RegResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegRespProto.RegResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegRespProto.RegResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegRespProto.RegResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RegRespProto.RegResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RegRespProto.RegResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RegRespProto.RegResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RegRespProto.RegResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RegRespProto.RegResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RegRespProto.RegResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RegRespProto.RegRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RegRespProto.internal_static_RegResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RegRespProto.internal_static_RegResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RegRespProto.RegResp.class, RegRespProto.RegResp.Builder.class);
      }

      // Construct using RegRespProto.RegResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        respCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        respContend_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RegRespProto.internal_static_RegResp_descriptor;
      }

      public RegRespProto.RegResp getDefaultInstanceForType() {
        return RegRespProto.RegResp.getDefaultInstance();
      }

      public RegRespProto.RegResp build() {
        RegRespProto.RegResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RegRespProto.RegResp buildPartial() {
        RegRespProto.RegResp result = new RegRespProto.RegResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.respCode_ = respCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.respContend_ = respContend_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RegRespProto.RegResp) {
          return mergeFrom((RegRespProto.RegResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RegRespProto.RegResp other) {
        if (other == RegRespProto.RegResp.getDefaultInstance()) return this;
        if (other.hasRespCode()) {
          setRespCode(other.getRespCode());
        }
        if (other.hasRespContend()) {
          bitField0_ |= 0x00000002;
          respContend_ = other.respContend_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRespCode()) {
          
          return false;
        }
        if (!hasRespContend()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RegRespProto.RegResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RegRespProto.RegResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 respCode = 1;
      private int respCode_ ;
      /**
       * <code>required int32 respCode = 1;</code>
       */
      public boolean hasRespCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 respCode = 1;</code>
       */
      public int getRespCode() {
        return respCode_;
      }
      /**
       * <code>required int32 respCode = 1;</code>
       */
      public Builder setRespCode(int value) {
        bitField0_ |= 0x00000001;
        respCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 respCode = 1;</code>
       */
      public Builder clearRespCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        respCode_ = 0;
        onChanged();
        return this;
      }

      // required string respContend = 2;
      private java.lang.Object respContend_ = "";
      /**
       * <code>required string respContend = 2;</code>
       */
      public boolean hasRespContend() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string respContend = 2;</code>
       */
      public java.lang.String getRespContend() {
        java.lang.Object ref = respContend_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          respContend_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string respContend = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRespContendBytes() {
        java.lang.Object ref = respContend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respContend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string respContend = 2;</code>
       */
      public Builder setRespContend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        respContend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string respContend = 2;</code>
       */
      public Builder clearRespContend() {
        bitField0_ = (bitField0_ & ~0x00000002);
        respContend_ = getDefaultInstance().getRespContend();
        onChanged();
        return this;
      }
      /**
       * <code>required string respContend = 2;</code>
       */
      public Builder setRespContendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        respContend_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegResp)
    }

    static {
      defaultInstance = new RegResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RegResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRegResp.proto\"0\n\007RegResp\022\020\n\010respCode\030\001" +
      " \002(\005\022\023\n\013respContend\030\002 \002(\tB\016B\014RegRespProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RegResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RegResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegResp_descriptor,
              new java.lang.String[] { "RespCode", "RespContend", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
